version: 0.0
os: linux
files:
  - source: /html
    destination: /var/www/html
  - source: /configs
    destination: /tmp/configs
hooks:
  BeforeInstall:
    - location: scripts/clearVarWWW.sh
  AfterInstall:
    - location: scripts/prepConfigs.sh
    - location: scripts/runResourceTest.sh
      timeout: 30
  ApplicationStart:
    - location: scripts/runAppTest.sh
      timeout: 30
  ValidateService:
    - location: scripts/monitorService.sh
      timeout: 30